development:
  adapter: mysql2
  database: paper_dev
  host: localhost
  password:
  encoding: utf8

test:
  adapter: mysql2
  database: paper_test
  host: localhost
  password:
  encoding: utf8

production:
  adapter: mysql2
  database: paperchest
  host: localhost
  password:
  encoding: utf8
